#! /bin/sh
gap=4
border=3

bspc monitor DP-4 -d I II III IV V VI VII
bspc monitor DVI-D-0 -d VIII IX X

#Border
bspc config border_width         $border
bspc config focused_border_color "#AA759F"
bspc config normal_border_color "#423654"

#Gap and padding
bspc config window_gap        $gap
bspc config top_padding		    -$gap
bspc config left_padding 	    -$gap
bspc config right_padding 	  -$gap
bspc config bottom_padding 	  -$gap

#Various settings
bspc config split_ratio		0.52
bspc config borderless_monocle	false
bspc config gapless_monocle	false
bspc config single_monocle	true
bspc config initial_polarity second_child

bspc rule -a steam state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a termite state=pseudo_tiled
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
